### ISSUE TITLE
Reconnection not being triggered when error occurs on connect

### ISSUE THREAD

**Issue by thrcorrea** [alexnfsc175/loopback-rabbitmq#23]
The retry connecting to the rabbitmq server seems to not work. If i start an connection attempt and the rabbitmq server is not reachable, the connector does not seem to try to reconnect, even with infinite retries. I coworker of mine posted a pull request with a possible solution. https://github.com/alexnfsc175/loopback-rabbitmq/pull/22

**Comment by alexnfsc175** [comment]
Pull request #22  has been merged, soon I will upload this update to npm, Thank you for your contribution.
